version: '3.8'
services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_USER: stat
      POSTGRES_PASSWORD: stat
      POSTGRES_DB: ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      retries: 10
      timeout: 5s
    volumes:
      - stats_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  ewm-db:
    container_name: ewm-db
    image: postgres:16.1
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: ewm-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      retries: 10
      timeout: 5s
    volumes:
      - ewm_db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ewm_db_data:
  stats_db_data: