grpc:
  server:
    port: 0

server:
  port: 0

kafka:
  producer:
    properties:
      bootstrap_server: localhost:9092
      key_serialize_class: org.apache.kafka.common.serialization.StringSerializer
      value_serialize_class: kafka.serialization.AvroSerializer
    topics:
      user-actions: stats.user-actions.v1