server:
  port: 9090

spring:
  application:
    name: stats-server

  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewm-stats
    username: stat
    password: stat

eureka:
  client:
    enabled: false