server:
  port: 0

spring:
  application:
    name: user-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6543/ewm-database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stats:
  client:
    serviceId: stats-server