CREATE TABLE IF NOT EXISTS participation_request
(
    id       BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL,
    event_id BIGINT      NOT NULL,
    status   VARCHAR(50) NOT NULL,
    created  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_event UNIQUE (user_id, event_id)
);