server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    config:
      enabled: false

    gateway:
      routes:
      - id: request_service_route
        uri: http://localhost:8082
        predicates:
          - Path=/participation-requests/**

      - id: request_service_user_events_route
        uri: http://localhost:8082
        predicates:
          - Path=/users/{userId}/events/{eventId}/requests

      - id: request_service_user_requests_route
        uri: http://localhost:8082
        predicates:
          - Path=/users/{userId}/requests/**

      - id: user_service_route
        uri: http://localhost:8083
        predicates:
          - Path=/admin/users/**

      - id: event_service_route
        uri: http://localhost:8081
        predicates:
          - Path=/**

eureka:
  client:
    enabled: false