CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS location
(
    id  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat decimal,
    lon decimal
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)  NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    category_id        BIGINT,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    location_id        BIGINT,
    is_paid            boolean,
    participant_limit  BIGINT,
    request_moderation boolean,
    creation_date      TIMESTAMP WITHOUT TIME ZONE,
    publication_date   TIMESTAMP WITHOUT TIME ZONE,
    state              VARCHAR(50)   NOT NULL,
    views              BIGINT,
    initiator_id       BIGINT,
    FOREIGN KEY (category_id) REFERENCES category (id),
    FOREIGN KEY (location_id) REFERENCES location (id)
);

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title  VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    FOREIGN KEY (compilation_id) REFERENCES compilation (id),
    FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT unique_compilation_event UNIQUE (compilation_id, event_id)
);